# Generated by Django 4.0.3 on 2022-04-10 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
